import type { MouseEvent, PointerEvent, WheelEvent } from 'react';
import type { Locale } from '../i18n';
import type { GridPoint } from '../simulation/navigation';
import { tacticalWizardTestMap, type SimulationOverlaySettings, type SupplyCacheView, type TacticalWizardAgentView, type TacticalWizardSimulationState } from '../simulation/tacticalWizardRuntime';
import { SimulationCanvas as BaseSimulationCanvas } from './SimulationTacticalCanvas';

const CELL = 22;
const OPERATIONS_STYLE = `.simulation-canvas-wrap{position:relative;line-height:0}.simulation-canvas-wrap>.simulation-canvas{position:relative;z-index:1}.simulation-operations-overlay{position:absolute;inset:0;width:100%;height:100%;z-index:2;pointer-events:none}.simulation-input-layer{position:absolute;inset:0;width:100%;height:100%;z-index:4;cursor:crosshair;touch-action:none}.sim-supply rect{fill:#17231d;stroke:#8fc19e;stroke-width:1.4}.sim-supply path{fill:none;stroke:#b8d9c1;stroke-width:1.1}.sim-supply text{fill:#c5d8cb;font-size:7.5px;paint-order:stroke;stroke:#091019;stroke-width:2px}.sim-supply-grenade rect{fill:#282217;stroke:#d1b86f}.sim-supply-grenade path{stroke:#e1ca87}.sim-supply-mixed rect{fill:#1d2130;stroke:#9caed9}.sim-supply-mixed path{stroke:#bac7e4}.sim-supply.depleted{opacity:.25}.sim-commander-marker circle{fill:none;stroke:#f1d37b;stroke-width:1.8;stroke-dasharray:3 3}.sim-commander-marker path{fill:#f1d37b;stroke:#091019;stroke-width:1}.sim-commander-marker text{fill:#f3dc94;font-size:8px;font-weight:800;paint-order:stroke;stroke:#091019;stroke-width:2px}.sim-resupply-route line{stroke:#7ec89a;stroke-width:1.8;stroke-dasharray:6 5}.sim-resupply-route circle{fill:none;stroke:#7ec89a;stroke-width:1.8;stroke-dasharray:3 3}.sim-resupply-route text{fill:#9edbb3;font-size:8px;font-weight:700;paint-order:stroke;stroke:#091019;stroke-width:2px}.sim-health-bg{fill:#091019;stroke:#314150;stroke-width:.8}.sim-health-fill{fill:#9ccf9d}.sim-health-low{fill:#dd9c6f}.sim-health-critical{fill:#df6e72}.sim-reaction line{stroke:#d5a96e;stroke-width:1.2;stroke-dasharray:3 3}.sim-reaction text{fill:#efc883;font-size:7.5px;font-weight:700;paint-order:stroke;stroke:#091019;stroke-width:2px}.sim-player-aim{stroke:#d8e1ea;stroke-width:1.25;stroke-dasharray:4 4;opacity:.72}.sim-player-shot{stroke:#fff2b6;stroke-width:2.5;filter:drop-shadow(0 0 2px #f4b85d)}.sim-aim-reticle circle,.sim-aim-reticle line{fill:none;stroke:#e7edf3;stroke-width:1.2}.sim-player-grenade-badge rect{fill:#0a1118;stroke:#9caed9;stroke-width:1}.sim-player-grenade-badge text{fill:#dbe4ec;font-size:8px;font-weight:700}.sim-effect-banner rect{fill:#0a1118;fill-opacity:.92;stroke:#c99e66;stroke-width:1}.sim-effect-banner text{fill:#e7c48a;font-size:8px;font-weight:700}.sim-input-capture{fill:transparent;pointer-events:all}`;

interface Props { readonly state: TacticalWizardSimulationState; readonly overlays: SimulationOverlaySettings; readonly onSetPlayer: (point: GridPoint) => void; readonly locale: Locale; }

export function SimulationCanvas(props: Props) {
  const { state, locale } = props;
  const width = tacticalWizardTestMap.width * CELL;
  const height = tacticalWizardTestMap.height * CELL;
  const help = locale === 'zh-CN' ? 'WASD / 方向键移动 · 鼠标瞄准 · 左键射击 · 右键投掷 · 滚轮切换投掷物 · Shift+左键调试传送 · Space 测试噪声' : 'WASD / arrows move · mouse aim · LMB fire · RMB throw · wheel cycles grenade · Shift+LMB debug teleport · Space test noise';
  const pointerPoint = (event: PointerEvent<SVGSVGElement> | MouseEvent<SVGSVGElement> | WheelEvent<SVGSVGElement>) => { const rect = event.currentTarget.getBoundingClientRect(); return { x: Math.max(0, Math.min(tacticalWizardTestMap.width - 0.01, (event.clientX - rect.left) / rect.width * tacticalWizardTestMap.width)), y: Math.max(0, Math.min(tacticalWizardTestMap.height - 0.01, (event.clientY - rect.top) / rect.height * tacticalWizardTestMap.height)) }; };
  const dispatchPoint = (name: string, point: GridPoint) => window.dispatchEvent(new CustomEvent<GridPoint>(name, { detail: point }));
  return <div className="simulation-canvas-wrap"><style>{`${OPERATIONS_STYLE}.simulation-page .map-help{font-size:0}.simulation-page .map-help::after{content:${JSON.stringify(help)};font-size:9px}`}</style><BaseSimulationCanvas {...props} /><svg className="simulation-operations-overlay" viewBox={`0 0 ${width} ${height}`} aria-hidden="true">{state.supplies.map((supply) => <SupplyMarker key={supply.id} supply={supply} locale={locale} />)}{state.agents.map((agent) => agent.commandRank === 'commander' ? <CommanderMarker key={`cmd-${agent.id}`} agent={agent} locale={locale} /> : null)}{state.agents.map((agent) => agent.logisticsTask !== 'none' && agent.resupplyTargetPosition !== null ? <ResupplyRoute key={`resupply-${agent.id}`} agent={agent} locale={locale} /> : null)}{state.agents.map((agent) => <HealthMarker key={`health-${agent.id}`} agent={agent} />)}{state.agents.map((agent) => agent.reactionState !== 'none' ? <ReactionMarker key={`reaction-${agent.id}`} agent={agent} locale={locale} /> : null)}{state.tacticalEffect.kind !== 'none' ? <TacticalEffectBanner state={state} locale={locale} width={width} /> : null}</svg><svg className="simulation-input-layer" viewBox={`0 0 ${width} ${height}`} aria-label={locale === 'zh-CN' ? '玩家战斗输入层' : 'Player combat input layer'} onPointerMove={(event) => dispatchPoint('volition-sim-aim', pointerPoint(event))} onClick={(event) => { const point = pointerPoint(event); if (event.shiftKey) props.onSetPlayer(point); else dispatchPoint('volition-sim-fire', point); }} onContextMenu={(event) => { event.preventDefault(); dispatchPoint('volition-sim-grenade', pointerPoint(event)); }} onWheel={(event) => { event.preventDefault(); window.dispatchEvent(new CustomEvent<number>('volition-sim-cycle-grenade', { detail: event.deltaY >= 0 ? 1 : -1 })); }}><rect className="sim-input-capture" width={width} height={height} /><PlayerCombatOverlay state={state} locale={locale} /></svg></div>;
}

function SupplyMarker({ supply, locale }: { readonly supply: SupplyCacheView; readonly locale: Locale }) { const p = center(supply.position); const label = supply.kind === 'ammo' ? (locale === 'zh-CN' ? '弹药' : 'AMMO') : supply.kind === 'grenade' ? (locale === 'zh-CN' ? '投掷物' : 'GREN') : (locale === 'zh-CN' ? '混合补给' : 'MIXED'); return <g className={`sim-supply sim-supply-${supply.kind}${supply.depleted ? ' depleted' : ''}`} transform={`translate(${p.x} ${p.y})`}><rect x={-9} y={-7} width={18} height={14} rx={3} /><path d="M -6 -3 L 6 -3 M -6 1 L 6 1 M 0 -5 L 0 5" /><text x={12} y={-2}>{supply.id} · {label}</text><text x={12} y={8}>{locale === 'zh-CN' ? `弹 ${supply.ammoRounds} / 雷 ${supply.grenades}` : `A ${supply.ammoRounds} / G ${supply.grenades}`}</text></g>; }
function CommanderMarker({ agent, locale }: { readonly agent: TacticalWizardAgentView; readonly locale: Locale }) { const p = center(agent.position); return <g className="sim-commander-marker" transform={`translate(${p.x} ${p.y})`}><circle r={14} /><path d="M -7 -15 L -4 -22 L 0 -17 L 4 -22 L 7 -15 Z" /><text x={12} y={-19}>{locale === 'zh-CN' ? '指挥官' : 'CMD'}</text></g>; }
function ResupplyRoute({ agent, locale }: { readonly agent: TacticalWizardAgentView; readonly locale: Locale }) { if (agent.resupplyTargetPosition === null) return null; const from = center(agent.position); const to = center(agent.resupplyTargetPosition); const label = agent.logisticsTask === 'resupply_ammo' ? (locale === 'zh-CN' ? '补弹' : 'RESUPPLY AMMO') : agent.logisticsTask === 'resupply_grenades' ? (locale === 'zh-CN' ? '补充投掷物' : 'RESUPPLY GRENADES') : (locale === 'zh-CN' ? '综合补给' : 'RESUPPLY'); return <g className="sim-resupply-route"><line x1={from.x} y1={from.y} x2={to.x} y2={to.y} /><circle cx={to.x} cy={to.y} r={13} /><text x={(from.x + to.x) / 2 + 5} y={(from.y + to.y) / 2 - 5}>{label}</text></g>; }
function HealthMarker({ agent }: { readonly agent: TacticalWizardAgentView }) { const p = center(agent.position); const width = 24; const ratio = agent.maxHealth <= 0 ? 0 : Math.max(0, Math.min(1, agent.health / agent.maxHealth)); const cls = ratio <= 0.3 ? 'sim-health-critical' : ratio <= 0.6 ? 'sim-health-low' : 'sim-health-fill'; return <g transform={`translate(${p.x - width / 2} ${p.y + 15})`}><rect className="sim-health-bg" width={width} height={3.5} rx={1.5} /><rect className={cls} width={width * ratio} height={3.5} rx={1.5} /></g>; }
function ReactionMarker({ agent, locale }: { readonly agent: TacticalWizardAgentView; readonly locale: Locale }) { const from = center(agent.position); const to = agent.reactionTarget === null ? from : center(agent.reactionTarget); return <g className="sim-reaction">{agent.reactionTarget !== null ? <line x1={from.x} y1={from.y} x2={to.x} y2={to.y} /> : null}<text x={from.x + 12} y={from.y + 16}>{localizeReaction(agent.reactionState, locale)} · {agent.reactionTicks}</text></g>; }
function TacticalEffectBanner({ state, locale, width }: { readonly state: TacticalWizardSimulationState; readonly locale: Locale; readonly width: number }) { const label = state.tacticalEffect.kind === 'flash_push' ? (locale === 'zh-CN' ? '震撼窗口：接近 / 压迫' : 'FLASH WINDOW: PUSH') : state.tacticalEffect.kind === 'smoke_retreat' ? (locale === 'zh-CN' ? '烟幕窗口：后撤 / 重组' : 'SMOKE WINDOW: DISENGAGE') : (locale === 'zh-CN' ? '爆炸压制：保持 blast standoff' : 'FRAG SUPPRESSION: HOLD STANDOFF'); return <g className="sim-effect-banner" transform={`translate(${Math.max(10, width - 238)} 12)`}><rect width={226} height={24} rx={5} /><text x={8} y={15}>{label} · T-{state.tacticalEffect.remainingTicks}</text></g>; }
function PlayerCombatOverlay({ state, locale }: { readonly state: TacticalWizardSimulationState; readonly locale: Locale }) { const player = center(state.player); const aim = center(state.playerCombat.aimTarget); const selected = state.playerCombat.selectedGrenade; const count = state.playerCombat.grenadeInventory[selected]; return <g pointerEvents="none"><line className="sim-player-aim" x1={player.x} y1={player.y} x2={aim.x} y2={aim.y} /><g className="sim-aim-reticle" transform={`translate(${aim.x} ${aim.y})`}><circle r={8} /><line x1={-12} y1={0} x2={-5} y2={0} /><line x1={5} y1={0} x2={12} y2={0} /><line x1={0} y1={-12} x2={0} y2={-5} /><line x1={0} y1={5} x2={0} y2={12} /></g>{state.playerCombat.shotPulse > 0 && state.playerCombat.shotFrom !== null && state.playerCombat.shotTo !== null ? <line className="sim-player-shot" x1={center(state.playerCombat.shotFrom).x} y1={center(state.playerCombat.shotFrom).y} x2={center(state.playerCombat.shotTo).x} y2={center(state.playerCombat.shotTo).y} /> : null}<g className="sim-player-grenade-badge" transform={`translate(${player.x + 14} ${player.y + 9})`}><rect width={locale === 'zh-CN' ? 68 : 74} height={16} rx={4} /><text x={6} y={11}>{grenadeLabel(selected, locale)} × {count} · P {state.playerCombat.firePressure.toFixed(1)}</text></g></g>; }
function localizeReaction(reaction: TacticalWizardAgentView['reactionState'], locale: Locale): string { if (locale !== 'zh-CN') return reaction.replaceAll('_', ' ').toUpperCase(); return { none: '正常', dodge: '闪避枪线', stunned: '震撼失能', flash_push: '震撼后压近', smoke_retreat: '烟幕后撤', smoke_reposition: '烟幕换位', grenade_suppress: '爆炸压制等待', downed: '失能' }[reaction]; }
function grenadeLabel(kind: TacticalWizardSimulationState['playerCombat']['selectedGrenade'], locale: Locale): string { if (locale !== 'zh-CN') return kind.toUpperCase(); return kind === 'flash' ? '震撼' : kind === 'smoke' ? '烟幕' : '破片'; }
function center(point: GridPoint): GridPoint { return { x: point.x * CELL + CELL / 2, y: point.y * CELL + CELL / 2 }; }
