import { useRef, type MouseEvent, type PointerEvent, type WheelEvent } from 'react';
import type { Locale } from '../i18n';
import type { GridPoint } from '../simulation/navigation';
import { tacticalWizardTestMap, type SimulationOverlaySettings, type TacticalWizardSimulationState } from '../simulation/tacticalWizardRuntime';
import { SimulationCanvas as BaseSimulationCanvas } from './SimulationRecoveryCanvas';

const CELL = 22;
const WHEEL_DEBOUNCE_MS = 130;
interface Props { readonly state: TacticalWizardSimulationState; readonly overlays: SimulationOverlaySettings; readonly onSetPlayer: (point: GridPoint) => void; readonly locale: Locale; }
type PointerLikeEvent = PointerEvent<SVGSVGElement> | MouseEvent<SVGSVGElement> | WheelEvent<SVGSVGElement>;

/** Top-most combat input and threat-response surface. */
export function SimulationCanvas(props: Props) {
  const { state, locale } = props;
  const width = tacticalWizardTestMap.width * CELL;
  const height = tacticalWizardTestMap.height * CELL;
  const lastWheelAt = useRef(0);
  const threatClass = state.threatResponse.active ? ' threat-inferred' : '';
  const dispatchPoint = (name: string, point: GridPoint) => window.dispatchEvent(new CustomEvent<GridPoint>(name, { detail: point }));
  const eventPoint = (event: PointerLikeEvent): GridPoint => clientToWorldPoint(event.currentTarget, event.clientX, event.clientY);
  return <div className={`simulation-combat-wrap${threatClass}`}><style>{COMBAT_STYLE}</style><BaseSimulationCanvas {...props} /><svg className="simulation-combat-status" viewBox={`0 0 ${width} ${height}`} aria-hidden="true"><ThreatResponseOverlay state={state} locale={locale} width={width} /><RescueSecurityOverlay state={state} locale={locale} /></svg><svg className="simulation-combat-input" viewBox={`0 0 ${width} ${height}`} aria-label={locale === 'zh-CN' ? '玩家战斗输入层' : 'Player combat input layer'} onPointerMove={(event) => dispatchPoint('volition-sim-aim', eventPoint(event))} onClick={(event) => { const point = eventPoint(event); if (event.shiftKey) props.onSetPlayer(point); else dispatchPoint('volition-sim-fire', point); }} onContextMenu={(event) => { event.preventDefault(); dispatchPoint('volition-sim-grenade', eventPoint(event)); }} onWheel={(event) => { event.preventDefault(); const now = performance.now(); if (now - lastWheelAt.current < WHEEL_DEBOUNCE_MS) return; lastWheelAt.current = now; window.dispatchEvent(new CustomEvent<number>('volition-sim-cycle-grenade', { detail: event.deltaY >= 0 ? 1 : -1 })); }}><rect className="sim-input-capture" width={width} height={height} /><CorrectedPlayerCombatOverlay state={state} locale={locale} /></svg></div>;
}

export function svgLocalToWorld(local: GridPoint): GridPoint { return { x: clamp(local.x / CELL - 0.5, 0, tacticalWizardTestMap.width - 1), y: clamp(local.y / CELL - 0.5, 0, tacticalWizardTestMap.height - 1) }; }
function clientToWorldPoint(svg: SVGSVGElement, clientX: number, clientY: number): GridPoint { const matrix = svg.getScreenCTM(); if (matrix !== null) { const point = svg.createSVGPoint(); point.x = clientX; point.y = clientY; const local = point.matrixTransform(matrix.inverse()); return svgLocalToWorld({ x: local.x, y: local.y }); } const rect = svg.getBoundingClientRect(); return svgLocalToWorld({ x: (clientX - rect.left) / Math.max(rect.width, 1) * tacticalWizardTestMap.width * CELL, y: (clientY - rect.top) / Math.max(rect.height, 1) * tacticalWizardTestMap.height * CELL }); }
function CorrectedPlayerCombatOverlay({ state, locale }: { readonly state: TacticalWizardSimulationState; readonly locale: Locale }) { const player = center(state.player); const aim = center(state.playerCombat.aimTarget); const selected = state.playerCombat.selectedGrenade; const count = state.playerCombat.grenadeInventory[selected]; return <g pointerEvents="none"><line className="sim-combat-player-aim" x1={player.x} y1={player.y} x2={aim.x} y2={aim.y} /><g className="sim-combat-reticle" transform={`translate(${aim.x} ${aim.y})`}><circle r={8} /><line x1={-13} y1={0} x2={-5} y2={0} /><line x1={5} y1={0} x2={13} y2={0} /><line x1={0} y1={-13} x2={0} y2={-5} /><line x1={0} y1={5} x2={0} y2={13} /><circle r={1.4} className="sim-combat-reticle-core" /></g>{state.playerCombat.shotPulse > 0 && state.playerCombat.shotFrom !== null && state.playerCombat.shotTo !== null ? <line className="sim-combat-player-shot" x1={center(state.playerCombat.shotFrom).x} y1={center(state.playerCombat.shotFrom).y} x2={center(state.playerCombat.shotTo).x} y2={center(state.playerCombat.shotTo).y} /> : null}<g className="sim-combat-grenade-badge" transform={`translate(${player.x + 14} ${player.y + 9})`}><rect width={locale === 'zh-CN' ? 75 : 82} height={16} rx={4} /><text x={6} y={11}>{grenadeLabel(selected, locale)} × {count} · P {state.playerCombat.firePressure.toFixed(1)}</text></g></g>; }
function ThreatResponseOverlay({ state, locale, width }: { readonly state: TacticalWizardSimulationState; readonly locale: Locale; readonly width: number }) { const threat = state.threatResponse; if (!threat.active || threat.estimatedSector === null) return null; const estimate = center(threat.estimatedSector); const source = threat.sourceAgentId === null ? null : state.agents.find((agent) => agent.id === threat.sourceAgentId) ?? null; const from = source === null ? null : center(source.position); const phase = threat.phase === 'break_contact' ? (locale === 'zh-CN' ? '反伏击：脱离枪线' : 'COUNTER-AMBUSH: BREAK CONTACT') : (locale === 'zh-CN' ? '反伏击：搜索推测扇区' : 'COUNTER-AMBUSH: SEARCH INFERRED SECTOR'); return <g className="sim-combat-threat">{from !== null ? <><line className="sim-combat-bearing" x1={from.x} y1={from.y} x2={estimate.x} y2={estimate.y} /><circle className="sim-combat-hit-origin" cx={from.x} cy={from.y} r={14} /></> : null}<circle className="sim-combat-threat-sector" cx={estimate.x} cy={estimate.y} r={32} /><circle className="sim-combat-threat-sector-inner" cx={estimate.x} cy={estimate.y} r={10} /><text className="sim-combat-threat-label" x={estimate.x + 15} y={estimate.y - 14}>{locale === 'zh-CN' ? '推测来袭扇区' : 'INFERRED FIRE SECTOR'}</text>{Object.entries(threat.defensiveCoverTargets).map(([id, point]) => { const agent = state.agents.find((entry) => entry.id === id); if (agent === undefined) return null; const a = center(agent.position); const b = center(point); return <g key={`break-${id}`} className="sim-combat-break-route"><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} /><rect x={b.x - 6} y={b.y - 6} width={12} height={12} rx={3} /></g>; })}<g className="sim-combat-threat-banner" transform={`translate(${Math.max(10, width - 278)} 72)`}><rect width={266} height={28} rx={5} /><text x={8} y={17}>{phase}{threat.smokeDeployed ? (locale === 'zh-CN' ? ' · 烟幕已投放' : ' · SMOKE DEPLOYED') : ''}</text></g></g>; }
function RescueSecurityOverlay({ state, locale }: { readonly state: TacticalWizardSimulationState; readonly locale: Locale }) { const target = state.threatResponse.rescueCoverTarget; const covererId = state.recovery.covererId; if (target === null || covererId === null) return null; const coverer = state.agents.find((agent) => agent.id === covererId); if (coverer === undefined) return null; const from = center(coverer.position); const to = center(target); return <g className="sim-combat-rescue-security"><line x1={from.x} y1={from.y} x2={to.x} y2={to.y} /><rect x={to.x - 8} y={to.y - 8} width={16} height={16} rx={3} /><text x={to.x + 12} y={to.y + 3}>{locale === 'zh-CN' ? '第三人掩护位' : 'SECURITY POSITION'}</text>{state.threatResponse.rescueInterruptedCount > 0 ? <text className="sim-combat-interrupt" x={to.x + 12} y={to.y + 15}>{locale === 'zh-CN' ? `救治中断 ×${state.threatResponse.rescueInterruptedCount}` : `RESCUE INTERRUPTED ×${state.threatResponse.rescueInterruptedCount}`}</text> : null}</g>; }
function grenadeLabel(kind: TacticalWizardSimulationState['playerCombat']['selectedGrenade'], locale: Locale): string { if (locale !== 'zh-CN') return kind.toUpperCase(); return kind === 'flash' ? '震撼' : kind === 'smoke' ? '烟幕' : '破片'; }
function center(point: GridPoint): GridPoint { return { x: point.x * CELL + CELL / 2, y: point.y * CELL + CELL / 2 }; }
function clamp(value: number, min: number, max: number): number { return Math.max(min, Math.min(max, value)); }

const COMBAT_STYLE = `
.simulation-combat-wrap{position:relative;line-height:0}.simulation-combat-wrap .simulation-input-layer{display:none!important}.simulation-combat-wrap.threat-inferred .squad-memory{display:none!important}.simulation-combat-status,.simulation-combat-input{position:absolute;inset:0;width:100%;height:100%}.simulation-combat-status{z-index:5;pointer-events:none}.simulation-combat-input{z-index:6;cursor:crosshair;touch-action:none}.simulation-combat-input .sim-input-capture{fill:transparent;pointer-events:all}.sim-combat-player-aim{stroke:#d8e1ea;stroke-width:1.25;stroke-dasharray:4 4;opacity:.72}.sim-combat-player-shot{stroke:#fff2b6;stroke-width:2.5;filter:drop-shadow(0 0 2px #f4b85d)}.sim-combat-reticle circle,.sim-combat-reticle line{fill:none;stroke:#f2f6fa;stroke-width:1.2}.sim-combat-reticle .sim-combat-reticle-core{fill:#f2f6fa;stroke:none}.sim-combat-grenade-badge rect{fill:#0a1118;stroke:#9caed9;stroke-width:1}.sim-combat-grenade-badge text{fill:#dbe4ec;font-size:8px;font-weight:700}.sim-combat-bearing{stroke:#e2a36f;stroke-width:2;stroke-dasharray:8 5}.sim-combat-hit-origin{fill:none;stroke:#e2a36f;stroke-width:1.4;stroke-dasharray:3 3}.sim-combat-threat-sector{fill:#d8945c;fill-opacity:.06;stroke:#e2a36f;stroke-width:2;stroke-dasharray:8 5}.sim-combat-threat-sector-inner{fill:none;stroke:#e9b27c;stroke-width:1.2}.sim-combat-threat-label{fill:#efbd8d;font-size:8px;font-weight:800;paint-order:stroke;stroke:#091019;stroke-width:2px}.sim-combat-break-route line{stroke:#d7a775;stroke-width:1.3;stroke-dasharray:4 4}.sim-combat-break-route rect{fill:#1a1e22;stroke:#d7a775;stroke-width:1.4}.sim-combat-threat-banner rect{fill:#0c1218;fill-opacity:.94;stroke:#d79c68;stroke-width:1}.sim-combat-threat-banner text{fill:#e9ba8e;font-size:8px;font-weight:800}.sim-combat-rescue-security line{stroke:#83c59c;stroke-width:1.8;stroke-dasharray:5 4}.sim-combat-rescue-security rect{fill:#12251b;stroke:#86c89f;stroke-width:1.5}.sim-combat-rescue-security text{fill:#a8d8b9;font-size:8px;font-weight:800;paint-order:stroke;stroke:#091019;stroke-width:2px}.sim-combat-rescue-security .sim-combat-interrupt{fill:#e7a080}
`;
