import { type ChangeEvent, useState } from 'react';
import type { Locale, Translate } from '../i18n';
import { localizedIntent, localizedTactic } from '../assetLocalization';
import { createBlankProject, parseWorkbenchProject, tacticalWizardExampleProject, type WorkbenchProject } from '../projects';
import { tacticalWizardTestMap, type TacticalWizardSimulationState } from '../simulation/tacticalWizardSimulation';
import { Metric } from '../components/Inspectors';

export function ProjectHub({ t, locale, localProjects, onSelect, onCreate, onImport }: { readonly t: Translate; readonly locale: Locale; readonly localProjects: readonly WorkbenchProject[]; readonly onSelect: (project: WorkbenchProject) => void; readonly onCreate: (project: WorkbenchProject) => void; readonly onImport: (project: WorkbenchProject) => void }) {
  const [name, setName] = useState('My Game AI'); const L = (zh: string, en: string) => locale === 'zh-CN' ? zh : en;
  const openProjectFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; try { onImport(parseWorkbenchProject(await file.text())); } catch (error) { window.alert(error instanceof Error ? error.message : String(error)); } event.target.value = ''; };
  return <section className="page-stack"><div className="section-heading"><div><h2>{t('projectLibrary')}</h2><p>{t('localDescription')}</p></div></div><div className="project-grid"><button className="project-card featured" onClick={() => onSelect(tacticalWizardExampleProject)}><span className="card-kicker">{t('builtInExample')}</span><strong>{locale === 'zh-CN' ? '战术巫师 AI' : 'Tactical Wizard AI'}</strong><p>{t('exampleDescription')}</p><span className="card-link">{L('打开示例 →', 'Open example →')}</span></button>{localProjects.map((entry) => <button key={entry.id} className="project-card" onClick={() => onSelect(entry)}><span className="card-kicker">{t('localProject')}</span><strong>{locale === 'zh-CN' && entry.nameZh ? entry.nameZh : entry.name}</strong><p>{entry.description}</p><span className="card-link">{L('打开 →', 'Open →')}</span></button>)}</div><div className="two-column"><section className="surface"><h3>{t('createProject')}</h3><label>{L('项目名称', 'Project name')}<input value={name} onChange={(event) => setName(event.target.value)} /></label><button className="primary-button" onClick={() => name.trim() && onCreate(createBlankProject(name.trim()))}>{t('createProject')}</button></section><section className="surface"><h3>{t('importProject')}</h3><p>{L('载入本地 willform.project.json 项目包。', 'Load a local willform.project.json package.')}</p><label className="file-button">{t('importProject')}<input type="file" accept="application/json,.json" onChange={openProjectFile} /></label></section></div></section>;
}

export function OverviewPage({ t, locale, project, simulation, onOpenSimulation }: { readonly t: Translate; readonly locale: Locale; readonly project: WorkbenchProject; readonly simulation: TacticalWizardSimulationState; readonly onOpenSimulation: () => void }) {
  const L = (zh: string, en: string) => locale === 'zh-CN' ? zh : en;
  const chain = locale === 'zh-CN' ? ['巡逻','调查','交替掩护','侧翼迂回','交叉火力','协同猛攻','分区搜索','重新编组'] : ['Patrol','Investigate','Bounding','Flank','Crossfire','Assault','Sector Sweep','Regroup'];
  return <section className="page-stack"><div className="overview-hero"><div><span className="card-kicker">{project.kind === 'built-in' ? t('builtInExample') : t('localProject')}</span><h2>{locale === 'zh-CN' && project.nameZh ? project.nameZh : project.name}</h2><p>{t('exampleDescription')}</p><div className="flow-line">{['Context','Observation','Memory / Belief','Decision','Intent','Host Action'].map((value, index) => <span key={value}>{index > 0 && <b>→ </b>}{value}</span>)}</div></div><button className="primary-button" onClick={onOpenSimulation}>▶ {t('simulation')}</button></div><div className="metric-grid"><Metric label={L('代理', 'Agents')} value={simulation.agents.length} detail={L('步枪战术小队', 'Rifle squad')} /><Metric label={t('currentIntent')} value={localizedIntent(simulation.selectedIntent, locale)} detail={`T${simulation.logicalTick}`} /><Metric label={t('tactic')} value={localizedTactic(simulation.squad.tactic, locale)} detail={`${L('轮次', 'cycle')} ${simulation.squad.maneuverCycle}`} /><Metric label={L('地图', 'Map')} value={`${tacticalWizardTestMap.width}×${tacticalWizardTestMap.height}`} detail="A* / LOS / sectors" /></div><div className="two-column"><section className="surface"><h3>{L('示例战术链', 'Example doctrine')}</h3><div className="behavior-chain">{chain.join(' → ')}</div></section><section className="surface"><h3>{L('Willform 边界', 'Willform boundary')}</h3><p>{t('simulationDescription')}</p><p>{t('privacyDescription')}</p></section></div></section>;
}
