import { type ChangeEvent, useState } from 'react';
import type { Locale, Translate } from '../i18n';
import { createBlankProject, parseWorkbenchProject, tacticalWizardExampleProject, type WorkbenchProject } from '../projects';
import { tacticalWizardTestMap, type TacticalWizardSimulationState } from '../simulation/tacticalWizardSimulation';
import { Metric } from '../components/Inspectors';

export function ProjectHub({ t, locale, localProjects, onSelect, onCreate, onImport }: { readonly t: Translate; readonly locale: Locale; readonly localProjects: readonly WorkbenchProject[]; readonly onSelect: (project: WorkbenchProject) => void; readonly onCreate: (project: WorkbenchProject) => void; readonly onImport: (project: WorkbenchProject) => void }) {
  const [name, setName] = useState('My Game AI');
  const openProjectFile = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]; if (!file) return;
    try { onImport(parseWorkbenchProject(await file.text())); } catch (error) { window.alert(error instanceof Error ? error.message : String(error)); }
    event.target.value = '';
  };
  return <section className="page-stack"><div className="section-heading"><div><h2>{t('projectLibrary')}</h2><p>{t('localDescription')}</p></div></div><div className="project-grid"><button className="project-card featured" onClick={() => onSelect(tacticalWizardExampleProject)}><span className="card-kicker">{t('builtInExample')}</span><strong>{locale === 'zh-CN' ? '战术巫师 AI' : 'Tactical Wizard AI'}</strong><p>{t('exampleDescription')}</p><span className="card-link">Open example →</span></button>{localProjects.map((entry) => <button key={entry.id} className="project-card" onClick={() => onSelect(entry)}><span className="card-kicker">{t('localProject')}</span><strong>{locale === 'zh-CN' && entry.nameZh ? entry.nameZh : entry.name}</strong><p>{entry.description}</p><span className="card-link">Open →</span></button>)}</div><div className="two-column"><section className="surface"><h3>{t('createProject')}</h3><label>Project name<input value={name} onChange={(event) => setName(event.target.value)} /></label><button className="primary-button" onClick={() => name.trim() && onCreate(createBlankProject(name.trim()))}>{t('createProject')}</button></section><section className="surface"><h3>{t('importProject')}</h3><p>Load a local <code>volition.project.json</code> package.</p><label className="file-button">{t('importProject')}<input type="file" accept="application/json,.json" onChange={openProjectFile} /></label></section></div></section>;
}

export function OverviewPage({ t, locale, project, simulation, onOpenSimulation }: { readonly t: Translate; readonly locale: Locale; readonly project: WorkbenchProject; readonly simulation: TacticalWizardSimulationState; readonly onOpenSimulation: () => void }) {
  return <section className="page-stack"><div className="overview-hero"><div><span className="card-kicker">{project.kind === 'built-in' ? t('builtInExample') : t('localProject')}</span><h2>{locale === 'zh-CN' && project.nameZh ? project.nameZh : project.name}</h2><p>{t('exampleDescription')}</p><div className="flow-line">{['Context','Observation','Memory / Belief','Decision','Intent','Host Action'].map((value, index) => <span key={value}>{index > 0 && <b>→ </b>}{value}</span>)}</div></div><button className="primary-button" onClick={onOpenSimulation}>▶ {t('simulation')}</button></div><div className="metric-grid"><Metric label="Agents" value={simulation.agents.length} detail="Rifle squad" /><Metric label={t('currentIntent')} value={simulation.selectedIntent} detail={`T${simulation.logicalTick}`} /><Metric label={t('tactic')} value={simulation.squad.tactic} detail={`phase ${simulation.squad.phase}`} /><Metric label="Map" value={`${tacticalWizardTestMap.width}×${tacticalWizardTestMap.height}`} detail="A* / LOS / cover" /></div><div className="two-column"><section className="surface"><h3>Example doctrine</h3><div className="behavior-chain">Patrol → Investigate → Bounding → Flank → Assault → Regroup / Search</div></section><section className="surface"><h3>Volition boundary</h3><p>{t('simulationDescription')}</p><p>{t('privacyDescription')}</p></section></div></section>;
}
