import { useEffect, useState, type ChangeEvent } from 'react';
import { validateProjectConfig, type VolitionProjectConfig } from '@volition/schema';
import type { Locale, Translate } from '../i18n';
import { createBlankProject, parseWorkbenchProject, serializeWorkbenchProject, tacticalWizardExampleProject, type WorkbenchProject } from '../projects';
import { tacticalWizardTestMap, type TacticalWizardSimulationState } from '../simulation/tacticalWizardSimulation';
import { Metric } from '../components/Inspectors';

export function ProjectHub({ t, locale, localProjects, onSelect, onCreate, onImport }: { readonly t: Translate; readonly locale: Locale; readonly localProjects: readonly WorkbenchProject[]; readonly onSelect: (project: WorkbenchProject) => void; readonly onCreate: (project: WorkbenchProject) => void; readonly onImport: (project: WorkbenchProject) => void }) {
  const [name, setName] = useState('My Game AI');
  const openProjectFile = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]; if (!file) return;
    try { onImport(parseWorkbenchProject(await file.text())); } catch (error) { window.alert(error instanceof Error ? error.message : String(error)); }
    event.target.value = '';
  };
  return <section className="page-stack"><div className="section-heading"><div><h2>{t('projectLibrary')}</h2><p>{t('localDescription')}</p></div></div><div className="project-grid"><button className="project-card featured" onClick={() => onSelect(tacticalWizardExampleProject)}><span className="card-kicker">{t('builtInExample')}</span><strong>{locale === 'zh-CN' ? '战术巫师 AI' : 'Tactical Wizard AI'}</strong><p>{t('exampleDescription')}</p><span className="card-link">Open example →</span></button>{localProjects.map((entry) => <button key={entry.id} className="project-card" onClick={() => onSelect(entry)}><span className="card-kicker">{t('localProject')}</span><strong>{locale === 'zh-CN' && entry.nameZh ? entry.nameZh : entry.name}</strong><p>{entry.description}</p><span className="card-link">Open →</span></button>)}</div><div className="two-column"><section className="surface"><h3>{t('createProject')}</h3><label>Project name<input value={name} onChange={(event) => setName(event.target.value)} /></label><button className="primary-button" onClick={() => name.trim() && onCreate(createBlankProject(name.trim()))}>{t('createProject')}</button></section><section className="surface"><h3>{t('importProject')}</h3><p>Load a local <code>volition.project.json</code> package.</p><label className="file-button">{t('importProject')}<input type="file" accept="application/json,.json" onChange={openProjectFile} /></label></section></div></section>;
}

export function OverviewPage({ t, locale, project, simulation, onOpenSimulation }: { readonly t: Translate; readonly locale: Locale; readonly project: WorkbenchProject; readonly simulation: TacticalWizardSimulationState; readonly onOpenSimulation: () => void }) {
  return <section className="page-stack"><div className="overview-hero"><div><span className="card-kicker">{project.kind === 'built-in' ? t('builtInExample') : t('localProject')}</span><h2>{locale === 'zh-CN' && project.nameZh ? project.nameZh : project.name}</h2><p>{t('exampleDescription')}</p><div className="flow-line">{['Context','Observation','Memory / Belief','Decision','Intent','Host Action'].map((value, index) => <span key={value}>{index > 0 && <b>→ </b>}{value}</span>)}</div></div><button className="primary-button" onClick={onOpenSimulation}>▶ {t('simulation')}</button></div><div className="metric-grid"><Metric label="Agents" value={simulation.agents.length} detail="Rifle squad" /><Metric label={t('currentIntent')} value={simulation.selectedIntent} detail={`T${simulation.logicalTick}`} /><Metric label={t('alertState')} value={simulation.squad.alertState} detail={`phase ${simulation.squad.phase}`} /><Metric label="Map" value={`${tacticalWizardTestMap.width}×${tacticalWizardTestMap.height}`} detail="Grid A* / LOS / cover" /></div><div className="two-column"><section className="surface"><h3>Example behavior</h3><div className="behavior-chain">Patrol → Investigate → Shared Alert → Cover / Bounding → Search → Patrol</div></section><section className="surface"><h3>Host boundary</h3><p>{t('simulationDescription')}</p><p>{t('privacyDescription')}</p></section></div></section>;
}

export function DesignPage({ t, config, setConfig, project, onSave, onReset }: { readonly t: Translate; readonly config: VolitionProjectConfig; readonly setConfig: (config: VolitionProjectConfig) => void; readonly project: WorkbenchProject; readonly onSave: () => void; readonly onReset: () => void }) {
  const [mode, setMode] = useState<'form' | 'json'>('form');
  const [jsonText, setJsonText] = useState(() => JSON.stringify(config, null, 2));
  const [validationMessage, setValidationMessage] = useState('');
  useEffect(() => setJsonText(JSON.stringify(config, null, 2)), [config]);
  const agent = config.agents[0]!;
  const setMemory = (key: 'decayPerSecond' | 'forgetBelowConfidence', value: number) => setConfig({ ...config, agents: config.agents.map((entry, index) => index === 0 ? { ...entry, memory: { ...entry.memory, [key]: value } } : entry) });
  const setScore = (key: string, value: number) => setConfig({ ...config, agents: config.agents.map((entry, index) => index === 0 ? { ...entry, decisionPolicy: { ...entry.decisionPolicy, config: { ...(entry.decisionPolicy.config ?? {}), [key]: value } } } : entry) });
  const applyJson = () => { try { const parsed = JSON.parse(jsonText) as VolitionProjectConfig; const result = validateProjectConfig(parsed); setValidationMessage(result.valid ? 'Schema valid.' : result.issues.map((issue) => `${issue.path}: ${issue.message}`).join(' · ')); if (result.valid) setConfig(parsed); } catch (error) { setValidationMessage(error instanceof Error ? error.message : String(error)); } };
  const exportProject = () => { const blob = new Blob([serializeWorkbenchProject({ ...project, config })], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'volition.project.json'; anchor.click(); URL.revokeObjectURL(url); };
  return <section className="page-stack"><div className="section-heading"><div><h2>{t('agentEditor')}</h2><p>{agent.displayName} · {agent.id}</p></div><div className="segmented"><button className={mode === 'form' ? 'active' : ''} onClick={() => setMode('form')}>{t('formEditor')}</button><button className={mode === 'json' ? 'active' : ''} onClick={() => setMode('json')}>{t('jsonEditor')}</button></div></div>{mode === 'form' ? <div className="design-grid"><section className="surface"><h3>{t('perception')}</h3><div className="tag-row">{agent.stimulusTypes.map((value) => <span key={value}>{value}</span>)}</div></section><section className="surface"><h3>{t('memory')}</h3><Num label="Decay / second" value={agent.memory.decayPerSecond} step={0.01} onChange={(value) => setMemory('decayPerSecond', value)} /><Num label="Forget below" value={agent.memory.forgetBelowConfidence} step={0.01} onChange={(value) => setMemory('forgetBelowConfidence', value)} /></section><section className="surface"><h3>{t('decision')}</h3><code>{agent.decisionPolicy.id}</code>{['engageScore','searchScore','investigateScore','patrolScore'].map((key) => <Num key={key} label={key} value={Number(agent.decisionPolicy.config?.[key] ?? 0)} step={1} onChange={(value) => setScore(key, value)} />)}</section><section className="surface"><h3>{t('behavior')}</h3>{Object.entries(agent.behaviors).map(([key, value]) => <div className="mapping-row" key={key}><span>{key}</span><code>{value}</code></div>)}</section><section className="surface"><h3>{t('capabilities')}</h3><div className="tag-row">{agent.capabilities.map((value) => <span key={value}>{value}</span>)}</div></section></div> : <section className="surface"><textarea className="code-editor" value={jsonText} onChange={(event) => setJsonText(event.target.value)} spellCheck={false} /><div className="action-row"><button className="primary-button" onClick={applyJson}>Validate & Apply</button><span>{validationMessage}</span></div></section>}<div className="action-row"><button className="primary-button" onClick={onSave}>{project.kind === 'built-in' ? t('duplicateProject') : 'Save locally'}</button><button className="secondary-button" onClick={exportProject}>{t('exportProject')}</button><button className="secondary-button" onClick={onReset}>{t('resetExample')}</button></div></section>;
}

function Num({ label, value, step, onChange }: { readonly label: string; readonly value: number; readonly step: number; readonly onChange: (value: number) => void }) { return <label>{label}<input type="number" value={value} step={step} onChange={(event) => onChange(Number(event.target.value))} /></label>; }
