import type { DecisionTrace } from '@volition/core';
import type { Locale, Translate } from '../i18n';
import type { GridPoint } from '../simulation/navigation';
import type { SimulationOverlaySettings, TacticalWizardSimulationState } from '../simulation/tacticalWizardRuntime';
import { DebugPage as BaseDebugPage, SimulationPage as BaseSimulationPage } from './RuntimeCombatPages';

interface SimulationProps { readonly t: Translate; readonly locale: Locale; readonly simulation: TacticalWizardSimulationState; readonly overlays: SimulationOverlaySettings; readonly setOverlays: (settings: SimulationOverlaySettings) => void; readonly playing: boolean; readonly setPlaying: (value: boolean) => void; readonly speed: number; readonly setSpeed: (value: number) => void; readonly onStep: () => void; readonly onReset: () => void; readonly onNoise: () => void; readonly onMove: (dx: number, dy: number) => void; readonly onSetPlayer: (point: GridPoint) => void; }

export function SimulationPage(props: SimulationProps) { return <div className="simulation-response-page"><ThreatResponsePanel simulation={props.simulation} locale={props.locale} /><BaseSimulationPage {...props} /></div>; }
export function DebugPage({ t, locale, simulation, traces }: { readonly t: Translate; readonly locale: Locale; readonly simulation: TacticalWizardSimulationState; readonly traces: readonly DecisionTrace[] }) { return <div className="page-stack"><ThreatResponsePanel simulation={simulation} locale={locale} compact /><BaseDebugPage t={t} locale={locale} simulation={simulation} traces={traces} /></div>; }

function ThreatResponsePanel({ simulation, locale, compact = false }: { readonly simulation: TacticalWizardSimulationState; readonly locale: Locale; readonly compact?: boolean }) {
  const L = (zh: string, en: string) => locale === 'zh-CN' ? zh : en;
  const threat = simulation.threatResponse; const recovery = simulation.recovery;
  const phase = threat.phase === 'none' ? L('无', 'none') : threat.phase === 'break_contact' ? L('脱离枪线', 'break contact') : L('推测扇区搜索', 'inferred-sector search');
  const source = shortActor(threat.sourceAgentId); const estimate = threat.estimatedSector === null ? '—' : `${threat.estimatedSector.x}, ${threat.estimatedSector.y}`; const bearing = threat.bearing === null ? '—' : `${threat.bearing.x.toFixed(2)}, ${threat.bearing.y.toFixed(2)}`; const coverer = shortActor(recovery.covererId); const rescuer = shortActor(recovery.rescuerId); const casualty = shortActor(recovery.downedAgentId); const coverTarget = threat.rescueCoverTarget === null ? '—' : `${threat.rescueCoverTarget.x}, ${threat.rescueCoverTarget.y}`;
  return <section className={`surface response-panel${compact ? ' compact' : ''}`}><style>{`.response-panel{display:grid;gap:8px;border-color:${threat.active ? '#7c5e45' : 'var(--border)'}.response-head{display:flex;justify-content:space-between;align-items:flex-start;gap:14px}.response-head strong{color:${threat.active ? '#e3b384' : '#9cafc0'}}.response-head p{margin:3px 0 0;color:#7f91a1;font-size:9px;line-height:1.45}.response-metrics{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:10px}.response-metrics small{font-size:8px;color:#8394a4}.response-metrics .active{color:#e0aa7c}.response-metrics .secure{color:#91c9a5}.response-contract{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.response-contract span{display:grid;gap:2px;padding:7px 9px;border:1px solid #283644;border-radius:7px;background:#0d141b}.response-contract small{font-size:7px;color:#718393}.response-contract b{font-size:9px;font-weight:600;color:#aebdca}@media(max-width:900px){.response-head{display:grid}.response-metrics{justify-content:flex-start}.response-contract{grid-template-columns:1fr}}`}</style><div className="response-head"><div><strong>⌁ {L('反伏击 / 救援安全契约', 'Counter-Ambush / Rescue Security')}</strong><p>{L('未确认射手的命中只生成“方向 + 粗略扇区”，不把隐藏玩家真实坐标写进认知。小队先脱离枪线，再用前出 / 掩护 / 卡位搜索该扇区；救治必须有独立第三人占据安全位。', 'An unseen hit produces only a bearing plus coarse sector, never the hidden player coordinate. The squad breaks contact first, then searches with lead / cover / overwatch. Casualty treatment requires a dedicated third-party security position.')}</p></div><div className="response-metrics"><small className={threat.active ? 'active' : ''}>{L('反伏击', 'Response')} {phase}</small><small>{L('首个受击者', 'Hit source')} {source}</small><small>{L('来袭方向', 'Bearing')} {bearing}</small><small>{L('推测扇区', 'Sector')} {estimate}</small><small>{L('应急烟幕', 'Smoke')} {threat.smokeDeployed ? `${L('已投放', 'deployed')} · ${shortActor(threat.smokeOwnerId)}` : L('未投放', 'none')}</small><small className={recovery.phase !== 'none' ? 'secure' : ''}>{L('救治中断', 'Rescue interrupts')} {threat.rescueInterruptedCount}</small></div></div>{!compact && (recovery.phase !== 'none' || threat.rescueInterruptedCount > 0) ? <div className="response-contract"><span><small>{L('伤员', 'Casualty')}</small><b>{casualty}</b></span><span><small>{L('救治者', 'Rescuer')}</small><b>{rescuer} · {recovery.phase}</b></span><span><small>{L('第三人掩护', 'Security')}</small><b>{coverer} → {coverTarget}</b></span></div> : null}</section>;
}
function shortActor(id: string | null): string { return id === null ? '—' : id.split(':').at(-1) ?? id; }
